[project]
name = "wxPython"
dynamic = [
    "description",
    "readme",
    "license",
    "authors",
    "keywords",
    "classifiers",
    "urls",
    "scripts",
    "dependencies",
    "version"
 ]
