[project]
name = "wxPython"
dynamic = ["license", "readme", "version"]
description = "Cross platform GUI toolkit for Python, \"Phoenix\" version"
# readme = "README.rst"
# license = "wxWindows Library License (https://opensource.org/licenses/wxwindows.php)"
authors = [
    { name = "Robin Dunn", email = "robin@alldunn.com" },
]
keywords = [
    "GUI",
    "awesome",
    "cross-platform",
    "user-interface",
    "wx",
    "wxWidgets",
    "wxWindows",
]
classifiers = [
    "Development Status :: 6 - Mature",
    "Environment :: MacOS X :: Cocoa",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications :: GTK",
    "Intended Audience :: Developers",
    "License :: OSI Approved",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 7",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: User Interfaces",
]
dependencies = [
    "numpy ; python_version >= '3.0' and python_version < '3.12'",
    "numpy < 1.17 ; python_version <= '2.7'",
    "six",
    "typing-extensions; python_version < '3.10'",
    # Wheel build requirement
    "attrdict3 ; sys_platform == 'win32'",

    # Other build requirements
    "appdirs",
    "setuptools",
    "sip == 6.9.1",

    "wheel",
    "twine",
    "requests",
    "requests[security]",
    "cython==3.0.10",
    "pytest",
    "pytest-xdist",
    "pytest-forked",
    "pytest-timeout",

    "sphinx==2.2.0 ; python_version >= '3.0'",
    "sphinx==1.8.5 ; python_version < '3.0'",
    "alabaster<0.7.14",
    "sphinxcontrib-applehelp<1.0.8",
    "sphinxcontrib-devhelp<1.0.6",
    "sphinxcontrib-htmlhelp<2.0.5",
    "sphinxcontrib-jsmath<1.0.2",
    "sphinxcontrib-qthelp<1.0.7",
    "sphinxcontrib-serializinghtml<1.1.10",
    "Jinja2==2.10",
    "markupsafe==1.1.1",
    "doc2dash==2.3.0",
    "beautifulsoup4",
    "typing-extensions; python_version < '3.10'",
]

[project.scripts]
helpviewer = "wx.tools.helpviewer:main"
img2png = "wx.tools.img2png:main"
img2py = "wx.tools.img2py:main"
img2xpm = "wx.tools.img2xpm:main"
pycrust = "wx.py.PyCrust:main"
pyshell = "wx.py.PyShell:main"
pyslices = "wx.py.PySlices:main"
pyslicesshell = "wx.py.PySlicesShell:main"
pywxrc = "wx.tools.pywxrc:main"
wxdemo = "wx.tools.wxget_docs_demo:demo_main"
wxdocs = "wx.tools.wxget_docs_demo:docs_main"
wxget = "wx.tools.wxget:main"

[project.urls]
Documentation = "https://docs.wxpython.org/"
Download = "https://pypi.org/project/wxPython"
Homepage = "http://wxPython.org/"
Source = "https://github.com/wxWidgets/Phoenix"


