[project]
name = "wxPython"
dynamic = ["version"]
description = "Cross platform GUI toolkit for Python, \"Phoenix\" version"
# readme = "README.rst"
# license = "wxWindows Library License (https://opensource.org/licenses/wxwindows.php)"
authors = [
    { name = "Robin Dunn", email = "robin@alldunn.com" },
]
keywords = [
    "GUI",
    "awesome",
    "cross-platform",
    "user-interface",
    "wx",
    "wxWidgets",
    "wxWindows",
]
classifiers = [
    "Development Status :: 6 - Mature",
    "Environment :: MacOS X :: Cocoa",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications :: GTK",
    "Intended Audience :: Developers",
    "License :: OSI Approved",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 7",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: User Interfaces",
]
dependencies = [
    "numpy ; python_version >= '3.0' and python_version < '3.12'",
    "numpy < 1.17 ; python_version <= '2.7'",
    "six",
    "typing-extensions; python_version < '3.10'",
]

[project.scripts]
helpviewer = "wx.tools.helpviewer:main"
img2png = "wx.tools.img2png:main"
img2py = "wx.tools.img2py:main"
img2xpm = "wx.tools.img2xpm:main"
pycrust = "wx.py.PyCrust:main"
pyshell = "wx.py.PyShell:main"
pyslices = "wx.py.PySlices:main"
pyslicesshell = "wx.py.PySlicesShell:main"
pywxrc = "wx.tools.pywxrc:main"
wxdemo = "wx.tools.wxget_docs_demo:demo_main"
wxdocs = "wx.tools.wxget_docs_demo:docs_main"
wxget = "wx.tools.wxget:main"

[project.urls]
Documentation = "https://docs.wxpython.org/"
Download = "https://pypi.org/project/wxPython"
Homepage = "http://wxPython.org/"
Source = "https://github.com/wxWidgets/Phoenix"


